name: Coverage
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "coverage"
  cancel-in-progress: true
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno test -R='.output/' -W='.output/' --coverage='coverage/' --reporter=dot
      - run: deno coverage --html coverage/
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "coverage/html/"
      - uses: actions/deploy-pages@v4
